# DO NOT EDIT THIS FILE BY HAND! Instead edit the R Markdown source file `Rmd/rstd.Rmd` and run `pkgpurl::purl_rmd()`.
# See `README.md#literate-programming` for more information on the literature programming approach used applying the R Markdown format.

utils::globalVariables(names = c(".",
                                 "Key",
                                 "is_pro"))

pkg <- utils::packageName()

.onUnload <- function (libpath) {
  pkgpins::unregister(pkg = pkg)
}

#' Test if RStudio is up to date
#'
#' @inheritParams latest_version
#' @param stable Set to `FALSE` in order to test against the latest [RStudio preview build](https://rstudio.com/products/rstudio/download/preview/) instead
#'   of the latest [stable build](https://rstudio.com/products/rstudio/download/).
#'
#' @return `TRUE` if the currently running RStudio version is the latest version, `FALSE` otherwise.
#' @export
is_uptodate <- function(stable = TRUE,
                        os = NULL) {
  
  rstudioapi::versionInfo()$version >= latest_version(type = rstudioapi::versionInfo()$mode,
                                                      stable = stable,
                                                      os = os)
}

#' Get latest RStudio version number
#'
#' @inheritParams releases
#' @param pro `TRUE` for the proprietary RStudio (Server) Pro edition and `FALSE` for the open-source RStudio (Server) edition.
#' @param os The OS _codename_ for which the RStudio version was built. If `NULL`, it will be auto-detected for the current system.
#'
#' @return `r pkgsnippets::return_label("version_nr")`
#' @export
#'
#' @examples
#' latest_version(os = "macos",
#'                use_cache = FALSE)
latest_version <- function(type = c("desktop", "server"),
                           stable = TRUE,
                           pro = FALSE,
                           os = NULL,
                           use_cache = TRUE,
                           cache_lifespan = "1 day") {
  data <-
    rlang::arg_match(type) %>%
    releases(stable = stable,
             use_cache = use_cache,
             cache_lifespan = cache_lifespan) %>%
    dplyr::filter(is_pro == checkmate::assert_flag(pro))
  
  supported_os <-
    data[["os"]] %>%
    unique() %>%
    setdiff(NA)
  
  if (!is.null(os)) {
    
    os <- rlang::arg_match(arg = os,
                           values = supported_os)
  } else {
    
    os <- dplyr::case_when(xfun::is_linux() ~ system2(command = "lsb_release",
                                                      args = "-cs",
                                                      stdout = TRUE,
                                                      stderr = TRUE),
                           xfun::is_macos() ~ "macos",
                           xfun::is_windows() ~ "windows")
    
    if (!(os %in% supported_os)) {
      
      rlang::abort(glue::glue("The RStudio release suited to your Linux distribution ", utils::sessionInfo("base")$running,
                              " codename \"{os}\" couldn't be auto-detected. Please set `os` to one of ", pal::prose_ls(supported_os,
                                                                                                                        wrap = '"',
                                                                                                                        last_separator = " or "), "."))
    }
  }
  
  data %>%
    dplyr::filter(os == os) %$%
    version %>%
    max() %>%
    unique() %>%
    as.numeric_version()
}

#' Get RStudio release metadata
#'
#' @param type Either `"desktop"` for [RStudio Desktop](https://rstudio.com/products/rstudio/#rstudio-desktop) or `"server"` for
#'   [RStudio Server](https://rstudio.com/products/rstudio/#rstudio-server) release metadata.
#' @param stable Set to `FALSE` to retrieve release metadata of [RStudio preview builds](https://rstudio.com/products/rstudio/download/preview/) instead of
#'   [stable builds](https://rstudio.com/products/rstudio/download/).
#' @param use_cache `r pkgsnippets::param_label("use_cache")`
#' @param cache_lifespan `r pkgsnippets::param_label("cache_lifespan")` Defaults to 1 day (24 hours).
#'
#' @return `r pkgsnippets::return_label("data")`
#' @export
#'
#' @examples
#' releases(type = "server",
#'          cache_lifespan = "1 year 2 months 3 weeks 4 days 5 hours 6 minutes 7 seconds")
releases <- function(type = c("desktop", "server"),
                     stable = TRUE,
                     use_cache = TRUE,
                     cache_lifespan = "1 day") {
  
  type <- rlang::arg_match(type)
  pin_name <- glue::glue("rstudio_releases_", dplyr::if_else(checkmate::assert_flag(stable),
                                                             type,
                                                             "preview"))
  
  if (checkmate::assert_flag(use_cache)) {
    
    result <- pkgpins::get_obj(id = pin_name,
                               max_age = cache_lifespan,
                               pkg = pkg)
    
    fetch <- is.null(result)
    
  } else {
    
    fetch <- TRUE
  }
  
  if (fetch) {
    
    result <- get_releases(type = type,
                           stable = stable)
  }
  
  if (use_cache) {
    pkgpins::cache_obj(x = result,
                       id = pin_name,
                       pkg = pkg)
  }
  
  result
}

get_releases <- function(type,
                         stable) {
  
  stable %>%
    dplyr::if_else(true = paste0("https://download", dplyr::if_else(type == "desktop", 1L, 2L), ".rstudio.org/"),
                   false = paste0("https://s3.amazonaws.com/rstudio-ide-build/")) %>%
    xml2::read_xml() %>%
    xml2::as_list() %>%
    purrr::keep(~ .x[["Name"]] == dplyr::if_else(stable,
                                                 glue::glue("rstudio-{type}"),
                                                 "rstudio-ide-build")) %>%
    purrr::chuck("ListBucketResult") %>%
    purrr::imap(~ { if (.y == "Contents") .x else NULL }) %>%
    purrr::compact() %>%
    purrr::map_depth(.depth = 2L,
                     .f = purrr::flatten_chr) %>%
    purrr::map_dfr(tibble::as_tibble) %>%
    dplyr::mutate(is_pro = stringr::str_detect(string = Key,
                                               pattern = "-pro-"),
                  os = stringr::str_extract(string = Key,
                                            pattern = "(?<=^desktop/)[^/]+(?=/)"),
                  version = Key %>% stringr::str_extract(pattern = "(?i)(?<=rstudio-(pro-)?)\\d+([\\.-]\\d+)*")) %>%
    dplyr::filter(Key != "current.ver")
}

#' Determine version of Pandoc bundled with RStudio
#'
#' @return `r pkgsnippets::return_label("version_nr")`
#' @export
bundled_pandoc_version <- function() {
  
  Sys.getenv("RSTUDIO_PANDOC") %>%
    fs::dir_ls(regexp = "pandoc(\\.exe)?$") %>%
    system2(args = "-v",
            stdout = TRUE,
            stderr = TRUE) %>%
    dplyr::first() %>%
    stringr::str_extract("\\d+(\\.\\d+)*") %>%
    as.numeric_version()
}
