# DO NOT EDIT THIS FILE BY HAND! Instead edit the R Markdown source file `Rmd/rstd.Rmd` and run `pkgpurl::purl_rmd()`.
# See `README.md#r-markdown-format` for more information on the literate programming approach used applying the R Markdown format.

# rstd: Unofficial Utility Functions Around the RStudio IDE
# Copyright (C) 2023 Salim Brüggemann
# 
# This program is free software: you can redistribute it and/or modify it under the terms of the GNU Affero General Public License as published by the Free
# Software Foundation, either version 3 of the License, or any later version.
# 
# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License along with this program. If not, see <https://www.gnu.org/licenses/>.

.onLoad <- function(libname, pkgname) {
  pkgpins::clear_cache(board = pkgpins::board(pkg = pkgname),
                       max_age = getOption(paste0(pkgname, ".max_cache_lifespan"),
                                           default = "30 days"))
}

utils::globalVariables(names = c(".",
                                 # tidyselect fns
                                 "everything",
                                 # other
                                 "is_pro",
                                 "key",
                                 "last_modified",
                                 "name"))

this_pkg <- utils::packageName()

#' Test if RStudio is up to date
#'
#' @inheritParams latest_version
#' @param stable Set to `FALSE` in order to test against the latest [RStudio preview build](https://rstudio.com/products/rstudio/download/preview/) instead
#'   of the latest [stable build](https://rstudio.com/products/rstudio/download/).
#'
#' @return `TRUE` if the currently running RStudio version is the latest version, `FALSE` otherwise.
#' @export
is_uptodate <- function(stable = TRUE,
                        os = NULL) {
  
  rstudioapi::versionInfo()$version >= latest_version(type = rstudioapi::versionInfo()$mode,
                                                      stable = stable,
                                                      os = os)
}

#' Get latest RStudio version number
#'
#' @inheritParams releases
#' @param pro `TRUE` for the proprietary RStudio (Server) Pro edition and `FALSE` for the open-source RStudio (Server) edition.
#' @param os The OS _codename_ for which the RStudio version was built. If `NULL`, it will be auto-detected for the current system.
#'
#' @return `r pkgsnip::return_label("version_nr")`
#' @export
#'
#' @examples
#' latest_version(os = "macos",
#'                use_cache = FALSE)
latest_version <- function(type = c("desktop", "server"),
                           stable = TRUE,
                           pro = FALSE,
                           os = NULL,
                           use_cache = TRUE,
                           cache_lifespan = "1 day") {
  
  checkmate::assert_flag(pro)
  
  data <-
    rlang::arg_match(type) %>%
    releases(stable = stable,
             use_cache = use_cache,
             cache_lifespan = cache_lifespan) %>%
    dplyr::filter(is_pro == pro)
  
  supported_os <-
    data[["os"]] %>%
    unique() %>%
    setdiff(NA)
  
  if (!is.null(os)) {
    
    os <- rlang::arg_match(arg = os,
                           values = supported_os)
  } else {
    
    os <-
      if (xfun::is_linux()) {
        system2(command = "lsb_release",
                args = "-cs",
                stdout = TRUE,
                stderr = TRUE)
      } else if (xfun::is_macos()) {
        "macos"
      } else if (xfun::is_windows()) {
        "windows"
      } else {
        cli::cli_abort("Unknown operating system detected.")
      }
    
    if (!(os %in% supported_os)) {
      
      cli::cli_abort(paste0("The RStudio release suited to your Linux distribution {.field {utils::sessionInfo('base')$running}} codename {.field {os}} ",
                            "couldn't be auto-detected. Please set {.arg os} to one of {.or {.val {supported_os}}}."))
    }
  }
  
  data %>%
    dplyr::filter(os == os) %$%
    version %>%
    max() %>%
    unique() %>%
    as.numeric_version()
}

#' Get RStudio release metadata
#'
#' @param type Either `"desktop"` for [RStudio Desktop](https://rstudio.com/products/rstudio/#rstudio-desktop) or `"server"` for
#'   [RStudio Server](https://rstudio.com/products/rstudio/#rstudio-server) release metadata.
#' @param stable Set to `FALSE` to retrieve release metadata of [RStudio preview builds](https://rstudio.com/products/rstudio/download/preview/) instead of
#'   [stable builds](https://rstudio.com/products/rstudio/download/).
#' @param use_cache `r pkgsnip::param_label("use_cache")`
#' @param cache_lifespan `r pkgsnip::param_label("cache_lifespan")` Defaults to 1 day (24 hours).
#'
#' @return `r pkgsnip::return_label("data")`
#' @export
#'
#' @examples
#' releases(type = "server",
#'          cache_lifespan = "1 year 2 months 3 weeks 4 days 5 hours 6 minutes 7 seconds")
releases <- function(type = c("desktop", "server"),
                     stable = TRUE,
                     use_cache = TRUE,
                     cache_lifespan = "1 day") {
  
  type <- rlang::arg_match(type)
  checkmate::assert_flag(stable)
  
  pkgpins::with_cache(expr = get_releases(type = type,
                                          stable = stable),
                      pkg = this_pkg,
                      from_fn = "releases",
                      stable,
                      use_cache = use_cache,
                      cache_lifespan = cache_lifespan)
}

get_releases <- function(type,
                         stable) {
  stable %>%
    ifelse(yes = paste0("https://download", ifelse(type == "desktop", 1L, 2L), ".rstudio.org/"),
           no = paste0("https://s3.amazonaws.com/rstudio-ide-build/")) %>%
    xml2::read_xml() %>%
    xml2::as_list() %>%
    purrr::keep(~ .x[["Name"]] == ifelse(stable,
                                         glue::glue("rstudio-{type}"),
                                         "rstudio-ide-build")) %>%
    purrr::chuck("ListBucketResult") %>%
    purrr::imap(~ {
      if (.y == "Contents") .x else NULL
    }) %>%
    purrr::compact() %>%
    purrr::map_depth(.depth = 2L,
                     .f = unlist) %>%
    purrr::map(tibble::as_tibble) %>%
    purrr::list_rbind() %>%
    dplyr::rename_with(.cols = everything(),
                       .fn = snakecase::to_snake_case) %>%
    dplyr::mutate(last_modified =
                    last_modified %>%
                    clock::naive_time_parse(format = "%Y-%m-%dT%H:%M:%SZ",
                                            precision = "millisecond") %>%
                    clock::time_point_round(precision = "second") %>%
                    clock::as_date_time(zone = "UTC"),
                  is_pro = stringr::str_detect(string = key,
                                               pattern = "-pro-"),
                  os = stringr::str_extract(string = key,
                                            pattern = "(?<=^desktop/)[^/]+(?=/)"),
                  version = stringr::str_extract(string = key,
                                                 pattern = "(?i)(?<=rstudio-((pro|server)-)?)\\d+([\\.-]\\d+)*")) %>%
    dplyr::filter(key != "current.ver")
}

#' Determine version of Pandoc bundled with RStudio
#'
#' @return `r pkgsnip::return_label("version_nr")`
#' @export
bundled_pandoc_version <- function() {
  
  Sys.getenv("RSTUDIO_PANDOC") %>%
    fs::dir_ls(regexp = "pandoc(\\.exe)?$") %>%
    system2(args = "-v",
            stdout = TRUE,
            stderr = TRUE) %>%
    dplyr::first() %>%
    stringr::str_extract("\\d+(\\.\\d+)*") %>%
    as.numeric_version()
}

#' List RStudio's R package dependencies' installation status
#'
#' @return `r pkgsnip::return_label("data")`
#' @export
pkg_status <- function() {
  
  rstudioapi::getRStudioPackageDependencies() %$%
    pal::is_pkg_installed(pkg = name,
                          min_version = version) %>%
    tibble::enframe(name = "package",
                    value = "is_installed")
}
